from openai import OpenAI
from dotenv import load_dotenv
import json
from functools import wraps

load_dotenv()

client = OpenAI()

# --- TOOL REGISTRY AND DECORATOR ---
TOOL_REGISTRY = {}


def register_tool(name, description, parameters):
    """Decorator to register a function as a callable tool."""
    def decorator(func):
        TOOL_REGISTRY[name] = {
            "func": func,
            "name": name,
            "description": description,
            "parameters": parameters
        }

        @wraps(func)
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)
        return wrapper
    return decorator

# --- DEFINE TOOLS ---


@register_tool(
    name="get_horoscope",
    description="Get today's horoscope for an astrological sign.",
    parameters={
        "type": "object",
        "properties": {
            "sign": {"type": "string", "description": "An astrological sign like Taurus or Aquarius"}
        },
        "required": ["sign"]
    }
)
def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."


# --- CREATE INPUT LIST ---
input_list = [
    {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
]

# --- CREATE TOOLS FOR OPENAI CALL ---
tools_for_model = [
    {
        "type": "function",
        "name": tool["name"],
        "description": tool["description"],
        "parameters": tool["parameters"],
    }
    for tool in TOOL_REGISTRY.values()
]

# --- FIRST MODEL CALL ---
response = client.responses.create(
    model="gpt-5-nano",
    tools=tools_for_model,
    input=input_list,
)

input_list += response.output

# --- HANDLE FUNCTION CALLS ---
for item in response.output:
    if item.type == "function_call":
        tool_name = item.name
        if tool_name in TOOL_REGISTRY:
            func = TOOL_REGISTRY[tool_name]["func"]
            args = json.loads(item.arguments)
            output_value = func(**args)

            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({tool_name: output_value})
            })

# --- SECOND MODEL CALL ---
response = client.responses.create(
    model="gpt-5-nano",
    instructions="Respond only with a horoscope generated by a tool.",
    tools=tools_for_model,
    input=input_list,
)

# --- OUTPUT ---
print("Final input:")
print(input)

print("\nFinal output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)
